"""add updated_at to user and remove onupdate from last_accessed

Revision ID: d82c8fda7f57
Revises: 1ac631b0884f
Create Date: 2026-07-29 07:50:40.996628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82c8fda7f57'
down_revision: Union[str, Sequence[str], None] = '1ac631b0884f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', 
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True), 
            server_default=sa.text('now()'), 
            nullable=False
        ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
