services:
  web:
    # build: .
    image: todo-app:latest
    container_name: todo_app
    ports:
      - "8000:8000"
    networks:
      - todo_network 
    env_file:
      - .env
    # command: >
    #   sh -c "
    #   echo 'Waiting for remote database...';
    #   until pg_isready -h $$LOCAL_DB_HOST -p $$LOCAL_DB_PORT -U $$LOCAL_DB_USER; do
    #     sleep 1;
    #   done;
    #   echo 'Database is ready! Starting application...';
    #   uv run app.main:app --host 0.0.0.0 --port 8000
    #   "

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - todo_network
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - todo_network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - todo_network
    ports:
      - "16686:16686" # Jaeger UI
    #   - "4317:4317"  # OTLP gRPC receiver (if bypassing collector)
    
    # environment:
    #   - SPAN_STORAGE_TYPE=badger # Changes storage from memory to Badger
    #   - BADGER_DIRECTORY_VALUE=/badger/data
    #   - BADGER_EPHEMERAL=false
    # volumes:
    #   - jaeger-data:/badger/data # Attaching volume for persistence

  locust-master:
    image: locustio/locust:latest
    container_name: locust-master
    ports:
      - "8089:8089"
      - "5557:5557"
      - "5558:5558"
    networks:
      - todo_network
    command: -f /mnt/locust/locustfile.py -H http://192.168.6.224:8000 --master --master-bind-host=0.0.0.0
    # running the workers as below manually
    # uv run locust -f ./tests/load/locustfile.py --worker --master-host 192.168.6.224 --master-port 5557 
    # TODO: Add a docker compose file in the load to spin up n required workers for locust load testing
    volumes:
      - ./tests/load/:/mnt/locust
    depends_on:
      - web

  web-locust-exporter:
    image:  containersol/locust_exporter:latest
    container_name: web-locust-exporter
    ports:
      - "9646:9646"
    networks:
      - todo_network
    command: --locust.uri=http://locust-master:8089
    depends_on:
      - locust-master

  web-otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: web-otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./infra/monitoring/otel-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4318:4318" # OTLP HTTP receiver
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - jaeger
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-storage:
  # jaeger-data:
  